### ISSUE TITLE
[Bug] Salvage drops does not work if the material is the same

### ISSUE THREAD

**Issue by StevenW-1** [zizmax/AcuteLoot#10]
If 2 drops in the salvage has the same material name, one of them wont work

```
        drop_1:
          material: "DIAMOND"
          name: "The item"
          command: "give {PLAYER} diamond 1"
        drop_2:
          material: "DIAMOND"
          name: "The broadcast"
          command: "broadcast Test message"
```
Drop 2 does not work, unless the material name is something else than DIAMOND

Plugin version: 2.0.2
Spigot version: Paperspigot 1.16.4
Errors: N/A
